### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by trbLeeciN** [mp035/hantek-365#1]
Hello there, 
Is it possible to use cli in windows with addition software or etc.?

**Comment by mp035** [comment]
Hi, You can possibly compile it with Cygwin.  There are no super-special dependencies.  Just libusb-1.0 which works on windows AFAIK.  The scons file would need some changes, but that is left as an exercise for the reader ;-).

**Comment by trbLeeciN** [comment]
Hello, I made it working, I used cygwin and mingw. Both of them works. But I suggest using mingw. When I create exe file by using cygwin, and use exe in another computer, I had to install cygwin too. But mingw doesn't require such thing, all you need to do is copy libusb-1.0.dll too.

**Comment by mp035** [comment]
@trbLeeciN That is fantastic.  Could you share your complete build process and the steps you went through to get it to work?    I can add them to the readme so other users on windows can benefit.

**Comment by trbLeeciN** [comment]
Things you need;
**Zadig**
https://zadig.akeo.ie/
Zadig used to change driver of Hantek, since Hantek365 driver can not be used, so we need to change Hantek driver as libusb driver. 
**Mingw**
http://www.mingw.org/
Mingw is C complier. Make sure you install gcc too,
I followed following guide to install Mingw. 
http://www.mingw.org/wiki/howto_install_the_mingw_gcc_compiler_suite
After these I added path of mingw path as system variable path. I am not sure if it is necessary or not, but I did it and it works. Guide to add path is below, many examples can be found for this.
https://www.rose-hulman.edu/class/csse/resources/MinGW/installation.htm
**Libusb Driver**
Libusb is available in windows as libusb-1.0.dll. You need to download it. And place in the same folder with your .c file.
https://libusb.info/
**Modified .C file**
To compily .c file you need some modifications. I used transfer_main.c file as main and modified it. You can find attached .c file in attachments.  (Thanks to CanKoçak)
I will add libusb driver for you in attachments.
Also I will add my exe file, so if you need you can use it. I changed output format since I will use it in another application.
**_So if all installed correctly, you will go to command prompt._**
in cmd: Go to source folder (where .c and .dll file is)
type:      gcc -o executable_filepath.exe source_filepath.c -lusb-1.0   
If you done everything right you will get .exe file in the same folder. After that you need to change hantek driver by using Zadig and you are ready to go.



[hantek_win.zip](https://github.com/mp035/hantek-365/files/2648732/hantek_win.zip)

**Comment by mp035** [comment]
Thank you for your contribution,  I have added your instruction to the readme.md file on the main project page (with credit).   Sorry it took me so long.
