### ISSUE TITLE
Ubuntu.... following setup... 

### ISSUE THREAD

**Issue by N3UE** [mp035/hantek-365#36]
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mp035** [comment]
[https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey)
