### ISSUE TITLE
I’m new to this 

### ISSUE THREAD

**Issue by CastroSATT** [mp035/hantek-365#7]
Can’t seem to get it to run the cli shows communication so that sides ok.. gui side is the issue I’m really new to node here’s my log.. if you can shed any light 

info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hantek-365@1.0.1~prestart: hantek-365@1.0.1
6 info lifecycle hantek-365@1.0.1~start: hantek-365@1.0.1
7 verbose lifecycle hantek-365@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle hantek-365@1.0.1~start: PATH: /usr/local/lib/node_modu$
9 verbose lifecycle hantek-365@1.0.1~start: CWD: /home/jma/Downloads/hante$
10 silly lifecycle hantek-365@1.0.1~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle hantek-365@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle hantek-365@1.0.1~start: Failed to exec start script
13 verbose stack Error: hantek-365@1.0.1 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modu$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modu$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/chil$
14 verbose pkgid hantek-365@1.0.1
15 verbose cwd /home/jma/Downloads/hantek-365-master/gui
16 verbose Linux 4.15.0-101-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.10.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by mp035** [comment]
did you run
`npm install`
first??

**Comment by CastroSATT** [comment]
Yep same order on a fresh lubuntu install not sure what I’m doing wrong 

I’ve included some screen shots of what I’m getting seems like I have an old version but I’m not sure as I said I’m far from my comfort zone of python heheheh 

JMA

**Comment by mp035** [comment]
Yeah, I understand.  I've found npm with electron to be quite cryptic regarding error messages.  Your screenshots do not seem to be attached.

**Comment by mp035** [comment]
Please also include the results of running `npm install`.  That is where the error usually lies.

**Comment by CastroSATT** [comment]
yeah screen shots didn't come through(side note the amount of security to even communicate is insane right now)

![unnamed-5](https://user-images.githubusercontent.com/31683024/84077398-2e664480-a9cf-11ea-9b80-265eae3ca3a3.png)
![unnamed-4](https://user-images.githubusercontent.com/31683024/84077406-30c89e80-a9cf-11ea-83b1-c1d2b43cf5bd.png)
![unnamed-3](https://user-images.githubusercontent.com/31683024/84077409-31613500-a9cf-11ea-8c9d-a1e3c17986cc.png)
![unnamed-2](https://user-images.githubusercontent.com/31683024/84077411-31f9cb80-a9cf-11ea-9588-989e6713015d.png)
![unnamed](https://user-images.githubusercontent.com/31683024/84077413-32926200-a9cf-11ea-872a-6105c3f1cd49.png)

**Comment by mp035** [comment]
Ok, so I can see at least 2 problems in the screenshots.
Firstly it looks like the install script doesn't have write access to the source directory tree.  Do:
`chmod -R a+rwx /home/jma/Downloads/hantek-365-master ` to allow writing of the source tree.

Secondly, it looks like you are using nodejs 8, and electron is asking for at least node version 10.  Don't use node/npm from the ubuntu repositories as it is grossly out of date.   Use NVM to manage your node installations.  Uninstall the version of node and npm you currently have installed, and follow the instructions here:
[https://nodesource.com/blog/installing-node-js-tutorial-using-nvm-on-mac-os-x-and-ubuntu/](https://nodesource.com/blog/installing-node-js-tutorial-using-nvm-on-mac-os-x-and-ubuntu/)
'Step 0' should be all you need.  Try the default LTS version (v12) and see if that works.  NVM should automatically give you a compatible npm with your node install.

**Comment by CastroSATT** [comment]
Cool sorted had the weirdest issue with electron it had permission issue used his command on the folder tried a reinstall then npm start worked first time. 

thanks 
![4F223747-1169-41BD-ADA2-10E8D2BC76CD](https://user-images.githubusercontent.com/31683024/84091784-69777080-a9ed-11ea-8453-e682b07ce0d0.png)

**Comment by CastroSATT** [comment]
Thanks I’m using this on a test rig before I move it to so
Thing a little more Permeant I’ve got it up and running now does it have Bluetooth support well I say that 

I’ve had a look and it seems that the supplied dongle (not opened yet ) auto connects with Bluetooth Module in the unit and supplies a pipe for the serial data I changed the usb pid on rules to see if it would work but it did not :-( having said that connecting a serial app to dongle comport at sending AT gives me somthing but I am at a loss 

My model 365F 

Pictures to follow  

JMA

**Comment by CastroSATT** [comment]
![0EC4F0A8-9C37-4869-B3F4-46E0B4565DE8](https://user-images.githubusercontent.com/31683024/84095449-45209180-a9f7-11ea-9230-c2b2aa33c4af.jpeg)
![B46AFB9C-681D-4821-B6C2-26BBC113116C](https://user-images.githubusercontent.com/31683024/84095458-4a7ddc00-a9f7-11ea-972b-fed90ca5e313.jpeg)
![484979CF-17EC-4B2A-8452-C848F0F7102A](https://user-images.githubusercontent.com/31683024/84095462-4baf0900-a9f7-11ea-9ed4-9799191faef1.jpeg)
![7022D906-4D25-4067-99B5-AA6F94D2057D](https://user-images.githubusercontent.com/31683024/84095466-4ce03600-a9f7-11ea-92c2-f9fcc949b544.jpeg)
![EC336093-6D48-41FB-A43C-25C34ACD40D3](https://user-images.githubusercontent.com/31683024/84095468-4e116300-a9f7-11ea-96ac-45bfa1e22cc7.jpeg)
![A5250CE1-31D0-438B-801C-FB64EE88893A](https://user-images.githubusercontent.com/31683024/84095469-4f429000-a9f7-11ea-997e-4867a6fec3ce.jpeg)
![D6F82637-E4E5-4B17-A638-54FB9F13FB90](https://user-images.githubusercontent.com/31683024/84095474-4fdb2680-a9f7-11ea-84fd-369dba91af7b.jpeg)
![4D5EE3CE-04D7-4950-96B1-5EA0AEC1B57E](https://user-images.githubusercontent.com/31683024/84095477-510c5380-a9f7-11ea-8eb1-27ddae8718e6.jpeg)
![DDF35227-AD3F-4CDF-8EB8-09694EE18DD8](https://user-images.githubusercontent.com/31683024/84095478-51a4ea00-a9f7-11ea-9c8e-2ddfa666a842.jpeg)

**Comment by mp035** [comment]
Your permissions are wrong on the USB device.  You have set PID "46aa" in the permissions file and PID "16aa" is what is showing on your screenshot.

**Comment by mp035** [comment]
That said.  It looks like your USB dongle is a CDC class device, so it is unlikely that it will be compatible with the implementation I wrote, however, it is probably very likely that the CDC stream is just a packeted version of the same data, so you could probably replace the readUsbDevice function in main.c with an appropriate implementation and everything else would fall into place.

**Comment by CastroSATT** [comment]
Thanks gives me a lot to chew on Not sure why they did it like this... with an extra dongle but I’ll take a look deeper over the next few weeks and see what I can set up.... that’s a big if

Thanks again 

JMA

**Comment by mp035** [comment]
If you want to work on BT compatibility please open a new issue.  Closing this for now.

**Comment by CastroSATT** [comment]
Cool thanks 

JMA
